from beam import *

b = Beam(12)
udl = UDL(4,6,4)
p1 = PointLoad(2,40, inverted=True, inclination=30)
p2 = PointLoad(b.length, 50, inverted=True)
m1 = PointMoment(2,20)
m2 = PointMoment(10, 20, ccw=False)
ra = Reaction(0, 'h', 'A')
rd = Reaction(8, 'r', 'D')

elements = (udl, p1, m1,m2, p2, ra, rd)
b.add_loads(elements)
b.add_moments(elements)
b.calculate_reactions((ra,rd))
b.generate_moment_equation(elements)
b.generate_shear_equation(elements)

x = np.linspace(-1, b.length, 1000)
plt.rc('font', family='serif', size=14)
fig, ax = plt.subplots(facecolor='w', edgecolor='w', num="BMD vs SFD")
ax.plot(x, b.mom_fn(x), label="BMD (kNm)")
ax.plot(x, b.shear_fn(x), label="SFD (kN)")
ax.set_xticks(np.arange(0, b.length+1,1))
ax.axhline(y=0, color='k', label='beam')
ax.set_title("BMD vs SFD of Beam")
ax.set_xlabel("x (m)")
ax.legend(fontsize=8)
ax.grid()
plt.savefig(f"Simply_Supported_Beam/generated_images/{__file__.split('/')[-1]}.png")
plt.show()